"""empty message

Revision ID: dbad10ab5ebb
Revises: 70955a65587b
Create Date: 2024-11-18 07:23:42.937791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbad10ab5ebb'
down_revision = '70955a65587b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('imageUrl',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('imageUrl',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
